# Generated by Django 5.2.6 on 2025-09-16 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_vendor_status_vendor_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('user', 'company')},
        ),
        migrations.AddField(
            model_name='vendor',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='role',
        ),
    ]
