# Generated by Django 5.2.6 on 2025-09-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('visa', 'Visa / Mastercard'), ('paypal', 'PayPal'), ('fawry', 'Fawry'), ('wallet', 'Wallet'), ('cash_on_delivery', 'Cash on Delivery'), ('apple_pay', 'Apple Pay')], max_length=20),
        ),
    ]
